dataset:
  eval_path: datasets/KITTI_TA_car_test_split
  dataset_path: datasets/kitti_test/images
  batch_size: 4
  num_workers: 2

model:
  model_name: lite_mono
  model_path: weights/lite_mono/8m_640x192

log:
  comet_ml_credentials: comet_ml_cred.json
  patch_checkpoint_dir: destination/checkpoints
  tensorboard_dir: destination/runs/train_adversarial
  log_interval: 2000

lists:
  30_rgb_triplets_path: lists/printable30values.txt 
  train_list: lists/train_list.txt
  eval_list: lists/car_dataset_test_12.txt

patch:
  path: patch-1106-litemono-far.jpg
  target_size: 0.09
  target_disp_sigmoid: 0.999999
  resolution: 256
  patch_augmentation:
    brightness: 0.1
    contrast: 0.1
  scene_augmentation:
    brightness: 0.1
    contrast: 0.1

  loss_weight:
    disp_loss: 1
    nps_loss: 0.01
    tv_loss: 0
    content_loss: 0.5

hyperparameter:
  num_epoch: 10
  learning_rate: 0.01

device: cuda:0