dataset:
  dataset_path: datasets/kitti_test/images
  batch_size: 16
  num_workers: 4

model:
  model_name: depth_hints
  model_path: weights/depth_hints/stereo_640x192_resnet50

log:
  comet_ml_credentials: comet_ml_cred.json
  patch_checkpoint_dir: destination/checkpoints
  tensorboard_dir: destination/runs/train_adversarial
  log_interval: 2000

lists:
  30_rgb_triplets_path: lists/printable30values.txt 
  train_list: lists/train_list.txt

patch:
  target_disp_sigmoid: 0.999999
  resolution: 256
  patch_augmentation:
    brightness: 0.1
    contrast: 0.1
  scene_augmentation:
    brightness: 0.1
    contrast: 0.1

  loss_weight:
    disp_loss: 2
    nps_loss: 1
    tv_loss: 0.5

hyperparameter:
  num_epoch: 5
  learning_rate: 0.01

device: cuda:0